version: "3.9"

services:

  node:
    container_name: node
    build:
        context: .
        dockerfile: DockerFile
    ports:
        - "3000:3000"

  nginx:
    image: nginx
    build:
        context: .
        dockerfile: Dockerfile-nginx
        args:
            - NODE_ENV=local
    container_name: nginx
    restart: always
    ports:
          - "80:80"
    volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080

  # mongodb:
  #   image: mongo
  #   restart: always
  #   container_name: mongodb
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: pass
  #     MONGO_INITDB_DATABASE: admin  

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: always
  #   ports:
  #     - 8082:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: pass
  #     ME_CONFIG_MONGODB_SERVER: mongodb
  #     # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

