FROM node:lts-alpine

WORKDIR /whatsapp-clone-projet

COPY whatsapp-clone
COPY whatsapp-clone-api 

RUN cd whatsapp-clone-api && npm install && npm run dev
RUN cd whatsapp-clone && npm install && npm run build

