FROM node:lts-alpine

WORKDIR /whatsapp-clone-projet


COPY /whatsapp-clone ./whatsapp-clone
COPY /whatsapp-clone-api ./whatsapp-clone-api



WORKDIR /whatsapp-clone-projet/whatsapp-clone 
# RUN cd whatsapp-clone 
RUN npm install
RUN npm run build

WORKDIR /whatsapp-clone-projet/whatsapp-clone-api 
RUN npm install 
# RUN npm run start
CMD [ "node", "index.js" ]
